### PR TITLE
Add Accessibility 

### PR DESCRIPTION
**Pull request by shahzaman900**
### Add accessibility
**In this PR I work on the accessibility of the website **

**Change Title**:
https://github.com/sheezu900/My_Potfolio/blob/d70f72a82bddaa54c6a06d9bab902589e1f6ea54/index.html#L15

**Image Alt Text**
- https://github.com/sheezu900/My_Potfolio/blob/d70f72a82bddaa54c6a06d9bab902589e1f6ea54/index.html#LL38C1-L52C12

- https://github.com/sheezu900/My_Potfolio/blob/d70f72a82bddaa54c6a06d9bab902589e1f6ea54/index.html#L58

- https://github.com/sheezu900/My_Potfolio/blob/d70f72a82bddaa54c6a06d9bab902589e1f6ea54/index.html#L90

- https://github.com/sheezu900/My_Potfolio/blob/d70f72a82bddaa54c6a06d9bab902589e1f6ea54/index.html#L157

- https://github.com/sheezu900/My_Potfolio/blob/d70f72a82bddaa54c6a06d9bab902589e1f6ea54/index.html#LL201C1-L214C1

- https://github.com/sheezu900/My_Potfolio/blob/d70f72a82bddaa54c6a06d9bab902589e1f6ea54/index.html#L232-L241

**Text headings** - no issues found

**Color contrast** - no issues found

**Resize** - no issues found

**Interaction** - no issues found

**Moving content** - no issues found

**Multimedia** - no issues found

**The basic structure of the page** - no issues found

### CODE REVIEW

**Review by wayungi — COMMENTED** [review]
Hi @sheezu900 , 
image

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [x] This is a pair programming project and you should have your partners commits as well especially since you made changes in more than one place.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by jecode93** [comment]
Hello @wayungi 

Thanks a lot for your review, we will do the changes as you request!

**Review by mckent05 — CHANGES_REQUESTED** [review]
Hi @sheezu900, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
almost there

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- You have done well making your site more accessible, 👍 👍 


## Required Changes ♻️
- According to the project requirements, In the result section of the report the student should include a statement pertaining to every point checked:
-- If everything was ok, they make a statement about that (e.g. "Page titles - no issues found").
-- If issues were found, they should link to the corresponding line of code in the Pull Request changes
Please include a report pertaining to the other points you were asked to check, e.g text headings, interactions e.t.c
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by LionRouge1 — APPROVED** [review]
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

done

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
